name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyze on SonarCloud
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CocoaPods
        run: pod install
        working-directory: Example

      - name: Download build-wrapper
        run: |
          curl -sSLo build-wrapper.zip https://sonarcloud.io/static/cpp/build-wrapper-macosx-x86.zip
          unzip build-wrapper.zip -d build-wrapper

      - name: Build with build-wrapper
        run: |
          ./build-wrapper/build-wrapper-macosx-x86 --out-dir bw-output \
          xcodebuild -workspace Example/healthvault-ios-sdk.xcworkspace \
          -scheme healthvault-ios-sdk-Example \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14'

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=meshvii_healthvault-ios-sdk
            -Dsonar.organization=meshvii
            -Dsonar.sources=HealthVault
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.cfamily.build-wrapper-output=bw-output
